### ISSUE TITLE
Activating this extension overrides title card formatting

### ISSUE THREAD

**Issue by adrm** [beingmrkenny/ListHighlighterForTrello#1]
I am using an userscript to be able to format the title of my cards with markdown. If this extension is active, the formatting appears correctly and instantly it is formatted back as normal text. The userscript I am using is https://gist.github.com/gorbiz/6062481

**Comment by beingmrkenny** [comment]
Hi Adrián,

Thanks for emailing me. I’m working on an update which should hopefully fix this issue. I hope to release it tomorrow.

Thanks,

Mark

**Comment by beingmrkenny** [comment]
Hi, 3.2.2 is out now and resolves this issue :)

**Comment by adrm** [comment]
Thanks a lot! It is indeed fixed.
