### ISSUE TITLE
Use `//` for notes instead of a heading

### ISSUE THREAD

**Issue by jaywick** [beingmrkenny/ListHighlighterForTrello#2]
Just a small idea, it would be neat to use `//` comment syntax to style a card as a sort of comment or note.

_Before_

![image](https://user-images.githubusercontent.com/3955052/40948047-60fa6e30-68a9-11e8-8cf7-4f0df2583c70.png)

_After_

![image](https://user-images.githubusercontent.com/3955052/40948042-583ae478-68a9-11e8-8dcb-660715eb13c6.png)

Will try and put together a PR if interested :)

**Comment by beingmrkenny** [comment]
Interesting suggestion. I'll have a think about how that might be incorporated. Reluctant to change established syntax, but could be offered as an user-changeable option. Thanks for getting in touch :)

**Comment by beingmrkenny** [comment]
Closing this as version 5 has removed header cards.
