### ISSUE TITLE
Support for a second highlight color

### ISSUE THREAD

**Issue by ErikMHummel** [beingmrkenny/ListHighlighterForTrello#3]
Hiya, I like highlight of my #doing column. It would be great if I could get a second color for my #waiting/#blocked column. Do you think that is doable?

**Comment by beingmrkenny** [comment]
Hi Erik,

This is a very common request, and I’m working on adding custom list highlighter colours for version 4. Can’t guarantee a release date, but hopefully in the next couple of months :)

Thanks for getting in touch!

**Comment by ErikMHummel** [comment]
Awesome @beingmrkenny! 🍻
