### ISSUE TITLE
Extension seems broken with new release

### ISSUE THREAD

**Issue by f-g-p** [beingmrkenny/ListHighlighterForTrello#7]
Hi,

It seems like Trello released a UI revamp recently, and the extension seems to have been broken since then.
Am I the only one facing this? 

Thanks for the extension btw, that's a cool one!

**Comment by teebui** [comment]
Mine also stopped working. It worked yesterday.

**Comment by tomeraviv** [comment]
It seems that Trello has removed the class names from the code.

before it was <div class="list-header" ... />
i think we could now use <div data-testid="list-header" .... />

(selector code is in /js/watch.js )

**Comment by beingmrkenny** [comment]
Hi,

Yes they've obfuscated class names, unfortunately.

Can you tell me the class name for the element you mentioned — .list-header

I'm seeing "bPNGI_VbtbXQ8v" — it would be useful to know if this is universal, or just me.

Currently looking into a number of ways to identify elements.

**Comment by probt** [comment]
My list-header class is also "bPNGI_VbtbXQ8v"; its sub div (with the header text) is "mKJWg6W_CLHoiO".

**Comment by beingmrkenny** [comment]
That's a good sign 🙂

**Comment by ryanbuening** [comment]
The new 5.0 version installed on Chrome for me and this issue seems fixed. Thanks @beingmrkenny!

**Comment by beingmrkenny** [comment]
Thanks for letting me know @ryanbuening, Chrome was the last browser to release this!
